### ISSUE TITLE
ERROR while implementing the code

### ISSUE THREAD

**Issue by VishnuVIVE** [tawfiqul-islam/RM_DeepRL#2]
Dear Sir,
I am trying to implement your Research article but i am getting issue kindly help me in resolving the issue.
i will be deeply indebted for your help.
ERROR:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tawfiq/PycharmProjects/RM_DeepRL/output/avg_returns_reinforce_beta_1.0.csv'

![ERROR](https://user-images.githubusercontent.com/106384938/170696168-f9e92e76-249a-48d1-858a-c458f639daeb.png)

**Comment by tawfiqul-islam** [comment]
In the settings/config.ini file, please modify the root variable to set the path of your project directory. Also, create an empty directory named 'output' in your project. For a reference, please check the output path shown in the error and check what is already written in the root variable in the config.ini

**Comment by VishnuVIVE** [comment]
Thank you so much sir
